name: CI for interpreter & tests

on:
  push:
    branches: [ main, wasm-3.0 ]
    paths: [ .github/**, interpreter/**, test/** ]

  pull_request:
    branches: [ main, wasm-3.0 ]
    paths: [ .github/**, interpreter/**, test/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  interpreter:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 24.0.0-v8-canary20241018c59bfa2926
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.x
      - name: Setup OCaml tools
        run: opam install --yes ocamlfind.1.9.5 js_of_ocaml.4.0.0 js_of_ocaml-ppx.4.0.0
      - name: Build interpreter
        run: cd interpreter && opam exec make
      - name: Setup node canary
        run: |
          cd $HOME
          wget https://nodejs.org/download/v8-canary/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz
          tar xf node-v${NODE_VERSION}-linux-x64.tar.xz
          stat $HOME/node-v${NODE_VERSION}-linux-x64/bin/node
      - name: Run tests
        run: |
          NODE="$HOME/node-v${NODE_VERSION}-linux-x64/bin/node --wasm-staging"
          cd interpreter && opam exec make "JS=$NODE" ci
